# Generated by Django 5.0.6 on 2024-06-13 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_categoryuser_category_subscribers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribers', through='news.CategoryUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
